# Generated by Django 4.0.1 on 2022-02-09 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tel', models.CharField(max_length=15, null=True)),
                ('dir', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('sueldo', models.IntegerField()),
                ('fecha_nac', models.DateField(verbose_name='YYYY-MM-DD')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nomina.empresa')),
            ],
        ),
    ]
